rsync -rlvz --ignore-existing --exclude='*cropped112.npy' /media/xinshuo/Data/Datasets/LRD/LRW/lipread_mp4 xinshuo@128.2.176.246:/media/hdd1/xinshuo/datasets/LRD/LRW/
rsync -rlvz --ignore-existing /media/xinshuo/Data/Datasets/LRD/LRW/lipread_mp4 xinshuo@128.2.194.87:/file3/xinshuo/data/datasets/LRD/LRW/
rsync -rlvz --ignore-existing xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/models/end_to_end_audiovisual_lipreading/finetuneGRU_last_frame /media/xinshuo/Data/models/end_to_end_audiovisual_lipreading/
rsync -rlvz --ignore-existing xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/models/end_to_end_audiovisual_lipreading/temporalConv /media/xinshuo/Data/models/end_to_end_audiovisual_lipreading/
rsync -rlvz --ignore-existing /media/xinshuo/Data/Datasets/LRD/LRW/lipread_mp4 xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/datasets/LRD/LRW/
rsync -rlvz --ignore-existing xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/models/end_to_end_audiovisual_lipreading/i3d_alone /media/xinshuo/Data/models/end_to_end_audiovisual_lipreading/
rsync -rlvz --ignore-existing xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/models/end_to_end_audiovisual_lipreading/backendGRU_every_frame /media/xinshuo/Data/models/end_to_end_audiovisual_lipreading/
rsync -rlvz --ignore-existing xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/models/end_to_end_audiovisual_lipreading/finetuneGRU_every_frame /media/xinshuo/Data/models/end_to_end_audiovisual_lipreading/
rsync -rlvz --ignore-existing xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/models/end_to_end_audiovisual_lipreading/i3d_BGRU /media/xinshuo/Data/models/end_to_end_audiovisual_lipreading/
rsync -rlvz --ignore-existing xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/models/end_to_end_audiovisual_lipreading/i3d_rgb_alone /media/xinshuo/Data/models/end_to_end_audiovisual_lipreading/
rsync -rlvz --ignore-existing xinshuo@128.2.177.239:/home/eshed1/Downloads/MATLAB_2018a_Licensing_Standard /home/xinshuo/Downloads/
rsync -rlvz --ignore-existing /media/xinshuo/Data/Datasets/LRD/LRW/centered96_rgb xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/datasets/LRD/LRW/
rsync -rlvz --ignore-existing /media/hdd1/xinshuo/data/datasets/LRD/LRW/centered96_rgb xinshuo@128.2.177.239:/home/xinshuo/datasets/LRD/LRW/
rsync -rlvz --ignore-existing /media/hdd1/xinshuo/data/datasets/LRD/LRW/centered96_rgb xinshuo@128.2.194.56:/home/xinshuo/datasets/LRD/LRW/
rsync -rlvz --ignore-existing /media/hdd1/xinshuo/data/datasets/LRD/LRW/centered96_rgb xinshuo@128.2.194.131:/mnt/hdd2/xinshuo/datasets/LRD/LRW/
rsync -rlvz --ignore-existing /media/hdd1/xinshuo/data/datasets/LRD/LRW/centered96_rgb xinshuo@128.2.177.239:/home/xinshuo/datasets/LRD/LRW/
rsync -rlvz --ignore-existing /media/xinshuo/Data/Datasets/KITTI/original_download xinshuo@128.2.177.239:/mnt/hdd2/xinshuo/datasets/KITTI/
rsync -rlvz --ignore-existing /media/xinshuo/Data/Datasets/LRD/LRW/lipread_mp4 xinshuo@128.2.176.246:/media/hdd1/xinshuo/data/datasets/LRD/LRW/
rsync -rlvz --ignore-existing /media/xinshuo/Data/Datasets/LRD/LRW/lipread_mp4 xinshuo@128.2.177.239:/mnt/hdd2/xinshuo/datasets/LRD/LRW/